// One-time: download self-hosted woff2 for the design-system typefaces and
// emit src/styles/fonts.css with @font-face rules pointing at /fonts/*.
// Weights (per brief §4.1):
//   Montserrat        300/500/600/700  — no italic
//   Cormorant Garamond 400/500/600 + italic 400/500
//   Source Serif 4     400/600      + italic 400
// Montserrat carries the headings and the tracked-uppercase label layer; it needs no
// italic because every italic display line on the site stays Cormorant. Its weights
// each have a job: 700 headings and titles, 600 the nav and tracked labels, 500 the
// unweighted UI text (buttons, dropdown links) that would otherwise resolve to a bolder
// cut. 300 exists solely for the brand lockup — "St" and "Church" are Light in the
// parish's logo artwork — so it is used nowhere else and stays out of the type scale.
import { writeFile, mkdir } from 'node:fs/promises';

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const FAMILIES = [
  {
    name: 'Montserrat',
    slug: 'montserrat',
    url: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;600;700&display=swap',
  },
  {
    name: 'Cormorant Garamond',
    slug: 'cormorant-garamond',
    url: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&display=swap',
  },
  {
    name: 'Source Serif 4',
    slug: 'source-serif-4',
    // request without the opsz axis so Google serves static woff2 per weight
    url: 'https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,wght@0,400;0,600;1,400&display=swap',
  },
];

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const FONT_DIR = 'public/fonts';
await mkdir(FONT_DIR, { recursive: true });

const blockRe = /\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g;
let css = '/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs */\n\n';

for (const fam of FAMILIES) {
  const res = await fetch(fam.url, { headers: { 'User-Agent': UA } });
  const text = await res.text();
  let m;
  while ((m = blockRe.exec(text)) !== null) {
    const subset = m[1].trim();
    if (!KEEP_SUBSETS.has(subset)) continue;
    const body = m[2];
    const style = (body.match(/font-style:\s*([^;]+);/) || [])[1]?.trim() || 'normal';
    const weight = (body.match(/font-weight:\s*([^;]+);/) || [])[1]?.trim() || '400';
    const range = (body.match(/unicode-range:\s*([^;]+);/) || [])[1]?.trim();
    const srcUrl = (body.match(/src:\s*url\(([^)]+)\)/) || [])[1];
    if (!srcUrl) continue;

    const file = `${fam.slug}-${weight}-${style}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(srcUrl, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(`${FONT_DIR}/${file}`, buf);

    css +=
      `@font-face {\n` +
      `  font-family: '${fam.name}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      (range ? `  unicode-range: ${range};\n` : ``) +
      `}\n\n`;
    console.log('downloaded', file, `(${buf.length} bytes)`);
  }
}

await mkdir('src/styles', { recursive: true });
await writeFile('src/styles/fonts.css', css);
console.log('wrote src/styles/fonts.css');
